# Generated by Django 6.0.3 on 2026-03-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_contentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], default='pending', max_length=20)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.contentitem')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.keyword')),
            ],
        ),
    ]
