# Generated by Django 6.0.3 on 2026-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
