# Generated by Django 6.0.3 on 2026-03-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_flag_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
